config/routes.rb
EmsHeros::Application.routes.draw do
  namespace :code do
    resources :codes
  end

  resources :trip_reports

end

app/models/trip_report.rb
# == Schema Information
#
# Table name: trip_reports
#
#  id         :integer          not null, primary key
#  run_number :integer
#  created_at :datetime
#  updated_at :datetime
#

class TripReport < ActiveRecord::Base
  
  has_one :patient, :class_name => "Patient::Patient"
  accepts_nested_attributes_for :patient

end

app/controllers/trip_reports_controller.rb
class TripReportsController < ApplicationController
  before_action :set_trip_report, only: [:show, :edit, :update, :destroy]

  # GET /trip_reports
  # GET /trip_reports.json
  def index
    @trip_reports = TripReport.all
  end

  # GET /trip_reports/1
  # GET /trip_reports/1.json
  def show
  end

  # GET /trip_reports/new
  def new
    @trip_report = TripReport.new
    @patient = Patient.new
  end

  # GET /trip_reports/1/edit
  def edit
  end

  # POST /trip_reports
  # POST /trip_reports.json
  def create
    @trip_report = TripReport.new(trip_report_params)

    respond_to do |format|
      if @trip_report.save
        format.html { redirect_to @trip_report, notice: 'Trip report was successfully created.' }
        format.json { render action: 'show', status: :created, location: @trip_report }
      else
        format.html { render action: 'new' }
        format.json { render json: @trip_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trip_reports/1
  # PATCH/PUT /trip_reports/1.json
  def update
    respond_to do |format|
      if @trip_report.update(trip_report_params)
        format.html { redirect_to @trip_report, notice: 'Trip report was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @trip_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trip_reports/1
  # DELETE /trip_reports/1.json
  def destroy
    @trip_report.destroy
    respond_to do |format|
      format.html { redirect_to trip_reports_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trip_report
      @trip_report = TripReport.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trip_report_params
      params.require(:trip_report).permit(:run_number)
    end
end

app/helpers/trip_reports_helper.rb
module TripReportsHelper
end

app/views/trip_reports/_form.html.erb
<%= form_for(@trip_report) do |f| %>
  <% if @trip_report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trip_report.errors.count, "error") %> prohibited this trip_report from being saved:</h2>

      <ul>
      <% @trip_report.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= fields_for @patient do |p| %>

  <% end %>
  
  <div class="field">
    <%= f.label :run_number %><br />
    <%= f.number_field :run_number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trip_reports/edit.html.erb
<h1>Editing trip_report</h1>

<%= render 'form' %>

<%= link_to 'Show', @trip_report %> |
<%= link_to 'Back', trip_reports_path %>

app/views/trip_reports/index.html.erb
<h1>Listing trip_reports</h1>

<table>
  <thead>
    <tr>
      <th>Run number</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @trip_reports.each do |trip_report| %>
    <tr>
      <td><%= trip_report.run_number %></td>
      <td><%= link_to 'Show', trip_report %></td>
      <td><%= link_to 'Edit', edit_trip_report_path(trip_report) %></td>
      <td><%= link_to 'Destroy', trip_report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to 'New Trip report', new_trip_report_path %>

app/views/trip_reports/new.html.erb
<h1>New trip_report</h1>

<%= render 'form' %>

<%= link_to 'Back', trip_reports_path %>

app/views/trip_reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Run number:</strong>
  <%= @trip_report.run_number %>
</p>


<%= link_to 'Edit', edit_trip_report_path(@trip_report) %> |
<%= link_to 'Back', trip_reports_path %>