config/routes.rb
EmsHeros::Application.routes.draw do
  namespace :code do
    resources :codes
  end

  resources :trip_reports

end

app/models/code.rb
module Code
  def self.table_name_prefix
    'code_'
  end
end

app/models/code/code.rb
# == Schema Information
#
# Table name: code_codes
#
#  id          :integer          not null, primary key
#  reference   :string(255)
#  description :string(255)
#  type        :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#

class Code::Code < ActiveRecord::Base
end

app/models/code/email.rb
# == Schema Information
#
# Table name: code_codes
#
#  id          :integer          not null, primary key
#  reference   :string(255)
#  description :string(255)
#  type        :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#

class Code::Email < Code::Code

end

app/models/code/not_value.rb
# == Schema Information
#
# Table name: code_codes
#
#  id          :integer          not null, primary key
#  reference   :string(255)
#  description :string(255)
#  type        :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#

class Code::NotValue < Code::Code

end

app/models/code/pertinent_negative.rb
# == Schema Information
#
# Table name: code_codes
#
#  id          :integer          not null, primary key
#  reference   :string(255)
#  description :string(255)
#  type        :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#

class Code::PertinentNegative < Code::Code

end

app/models/code/phone.rb
# == Schema Information
#
# Table name: code_codes
#
#  id          :integer          not null, primary key
#  reference   :string(255)
#  description :string(255)
#  type        :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#

class Code::Phone < Code::Code

end

app/models/code/race.rb
# == Schema Information
#
# Table name: code_codes
#
#  id          :integer          not null, primary key
#  reference   :string(255)
#  description :string(255)
#  type        :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#

class Code::Race < Code::Code

end

app/controllers/code/codes_controller.rb
class Code::CodesController < ApplicationController
  before_action :set_code_code, only: [:show, :edit, :update, :destroy]

  # GET /code/codes
  # GET /code/codes.json
  def index
    @code_codes = Code::Code.all
  end

  # GET /code/codes/1
  # GET /code/codes/1.json
  def show
  end

  # GET /code/codes/new
  def new
    @code_code = Code::Code.new
  end

  # GET /code/codes/1/edit
  def edit
  end

  # POST /code/codes
  # POST /code/codes.json
  def create
    @code_code = Code::Code.new(code_code_params)

    respond_to do |format|
      if @code_code.save
        format.html { redirect_to @code_code, notice: 'Code was successfully created.' }
        format.json { render action: 'show', status: :created, location: @code_code }
      else
        format.html { render action: 'new' }
        format.json { render json: @code_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /code/codes/1
  # PATCH/PUT /code/codes/1.json
  def update
    respond_to do |format|
      if @code_code.update(code_code_params)
        format.html { redirect_to @code_code, notice: 'Code was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @code_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /code/codes/1
  # DELETE /code/codes/1.json
  def destroy
    @code_code.destroy
    respond_to do |format|
      format.html { redirect_to code_codes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_code_code
      @code_code = Code::Code.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def code_code_params
      params.require(:code_code).permit(:reference, :description, :type)
    end
end

app/helpers/code/codes_helper.rb
module Code::CodesHelper
end

app/views/code/codes/_form.html.erb
<%= form_for(@code_code) do |f| %>
  <% if @code_code.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@code_code.errors.count, "error") %> prohibited this code_code from being saved:</h2>

      <ul>
      <% @code_code.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :reference %><br />
    <%= f.text_field :reference %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :type %><br />
    <%= f.text_field :type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/code/codes/edit.html.erb
<h1>Editing code_code</h1>

<%= render 'form' %>

<%= link_to 'Show', @code_code %> |
<%= link_to 'Back', code_codes_path %>

app/views/code/codes/index.html.erb
<h1>Listing code_codes</h1>

<table>
  <thead>
    <tr>
      <th>Reference</th>
      <th>Description</th>
      <th>Type</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @code_codes.each do |code_code| %>
    <tr>
      <td><%= code_code.reference %></td>
      <td><%= code_code.description %></td>
      <td><%= code_code.type %></td>
      <td><%= link_to 'Show', code_code %></td>
      <td><%= link_to 'Edit', edit_code_code_path(code_code) %></td>
      <td><%= link_to 'Destroy', code_code, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to 'New Code', new_code_code_path %>

app/views/code/codes/new.html.erb
<h1>New code_code</h1>

<%= render 'form' %>

<%= link_to 'Back', code_codes_path %>

app/views/code/codes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Reference:</strong>
  <%= @code_code.reference %>
</p>

<p>
  <strong>Description:</strong>
  <%= @code_code.description %>
</p>

<p>
  <strong>Type:</strong>
  <%= @code_code.type %>
</p>


<%= link_to 'Edit', edit_code_code_path(@code_code) %> |
<%= link_to 'Back', code_codes_path %>